name: Docker

on:
  push:
    tags: ['v*']
    branches: ['master']

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            apigen/apigen
            ghcr.io/apigen/apigen
          tags: |
            type=semver, pattern={{version}}
            type=semver, pattern={{major}}.{{minor}}
            type=semver, pattern={{major}}
            type=edge
            type=sha, format=long

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v3
        with:
          tags: ${{ steps.meta.outputs.tags }}
          build-args: COMPOSER_ROOT_VERSION=${{ github.ref_typ == 'tag' && github.ref_name || 'dev-master' }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
